<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Platform\Actions\ActionPlane;
use App\Platform\Actions\OpenApi\ActionOpenApi;
use Illuminate\Console\Command;
use Symfony\Component\Yaml\Yaml;

/**
 * Writes `resources/openapi/<plane>.yaml` — one document per {@see ActionPlane}, the
 * environment's and the workspace's — from the hand-written base and the action registry
 * ({@see ActionOpenApi}). `--check` writes nothing and fails when the committed
 * file is not what the build would produce — the CI gate that keeps them from drifting.
 */
final class BuildOpenApiCommand extends Command
{
    protected $signature = 'openapi:build {--check : Fail when the committed document is stale, without writing}';

    protected $description = 'Build the management API OpenAPI documents from their base and the action registry';

    public function handle(ActionOpenApi $openApi): int
    {
        $stale = [];

        foreach (ActionPlane::cases() as $plane) {
            $basePath = resource_path("openapi/base/{$plane->value}.yaml");
            $outPath = resource_path("openapi/{$plane->value}.yaml");

            /** @var array<string, mixed> $base */
            $base = Yaml::parseFile($basePath);

            $document = "# GENERATED by `php artisan openapi:build` from resources/openapi/base/{$plane->value}.yaml\n"
                ."# and the action registry (app/Actions). Edit the base or the action, never this file.\n"
                .Yaml::dump($openApi->build($base, $plane), 20, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK | Yaml::DUMP_OBJECT_AS_MAP | Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);

            $current = is_file($outPath) ? (string) file_get_contents($outPath) : '';

            if ($current === $document) {
                continue;
            }

            if ($this->option('check')) {
                $stale[] = $outPath;

                continue;
            }

            file_put_contents($outPath, $document);
            $this->components->info("Wrote {$outPath}.");
        }

        if ($stale !== []) {
            $this->components->error('Stale: '.implode(', ', $stale).'. Run `php artisan openapi:build` and commit the result.');

            return self::FAILURE;
        }

        if ($this->option('check')) {
            $this->components->info('OpenAPI documents are current.');
        }

        return self::SUCCESS;
    }
}
