<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Platform\Locale\HostedTranslations;
use Illuminate\Console\Command;

/**
 * Writes `resources/js/i18n/keys.ts` — the union of every key the hosted pages may ask
 * the translator for — from the ENGLISH catalogue under `lang/en/`.
 *
 * English is the source of truth for which keys exist; LangParityTest holds every other
 * language to exactly that set. So a page asking for a key English lacks fails `tsc`,
 * and a key English has that another language lacks fails the test suite — between them
 * no visitor ever reads a raw key.
 *
 * Reads the app's files directly rather than through the translator, which would merge in
 * the framework's own `auth.php` lines (`auth.failed`, …) that no page uses. `--check`
 * writes nothing and fails when the committed file is stale, for CI.
 */
final class GenerateI18nTypesCommand extends Command
{
    protected $signature = 'i18n:types {--check : Fail when the committed key type is stale, without writing}';

    protected $description = 'Generate the TypeScript message-key type for the hosted pages from lang/en';

    public function handle(): int
    {
        $out = resource_path('js/i18n/keys.ts');
        $document = self::render();
        $current = is_file($out) ? (string) file_get_contents($out) : '';

        if ($current === $document) {
            $this->components->info('The message-key type is current.');

            return self::SUCCESS;
        }

        if ($this->option('check')) {
            $this->components->error("Stale: {$out}. Run `php artisan i18n:types` and commit the result.");

            return self::FAILURE;
        }

        file_put_contents($out, $document);
        $this->components->info("Wrote {$out}.");

        return self::SUCCESS;
    }

    /** The file, exactly as committed — prettier-clean, so `format:check` agrees with it. */
    public static function render(): string
    {
        $keys = [];

        foreach (HostedTranslations::CLIENT_NAMESPACES as $namespace) {
            $path = lang_path("en/{$namespace}.php");

            if (! is_file($path)) {
                continue;
            }

            $lines = require $path;

            if (is_array($lines)) {
                $keys = [...$keys, ...array_keys(HostedTranslations::flatten($lines, $namespace))];
            }
        }

        sort($keys);

        $union = $keys === []
            ? ' never'
            : "\n".implode("\n", array_map(
                static fn (string $key): string => '    | '.self::quote($key),
                $keys,
            ));

        return '// GENERATED by `php artisan i18n:types` from lang/en/{'.implode(',', HostedTranslations::CLIENT_NAMESPACES)."}.php.\n"
            ."// Edit the English catalogue and regenerate; never this file.\n\n"
            ."/** Every key the hosted pages' translator accepts. */\n"
            ."export type MessageKey ={$union};\n";
    }

    private static function quote(string $key): string
    {
        return "'".str_replace(['\\', "'"], ['\\\\', "\\'"], $key)."'";
    }
}
