<?php

declare(strict_types=1);

namespace App\Platform\Portal;

use App\Console\Commands\BuildIdpGuideDocsCommand;
use Cbox\Id\Federation\Enums\GuideProtocol;
use Cbox\Id\Federation\Enums\GuideReturnKind;
use Cbox\Id\Federation\Enums\SpValue;
use Cbox\Id\Federation\IdentityProviderGuides;
use Cbox\Id\Federation\ValueObjects\GuideField;
use Cbox\Id\Federation\ValueObjects\IdentityProviderGuide;
use Cbox\Id\Federation\ValueObjects\ScimDirectoryGuide;

/**
 * THE IT ADMINISTRATOR'S IDENTITY PROVIDER PAGES, written from the framework's guides
 * ({@see IdentityProviderGuides}) by `php artisan docs:idp-guides`
 * ({@see BuildIdpGuideDocsCommand}).
 *
 * The Admin Portal draws the same guides — the same field labels, the same steps — so the
 * page somebody reads to prepare before they open the link cannot name a field the portal
 * does not, or a field the identity provider renamed upstream since. A guide the framework
 * adds gets a page the next time the build runs; `--check` and its test fail the day
 * somebody upgrades without running it.
 *
 * HAND-WRITTEN PAGES STAY HAND-WRITTEN. Okta, Microsoft Entra ID, Google Workspace and the
 * generic SAML, OpenID Connect and SCIM pages carry more than a guide does — certificate
 * renewal, Google's directory pull, what the assertion must hold — so they are linked from
 * the index rather than generated over ({@see self::HAND_WRITTEN}).
 *
 * The provider table on `_index.md` is generated too, between two markers, so the list of
 * providers there is the list the portal offers.
 *
 * Deterministic: catalogue order, no clock, no host. Values are described, never resolved
 * — a page is for every organization, and `https://…/sso/saml/…/acs` is the shape of the
 * one the portal shows.
 */
final class IdpGuideDocs
{
    public const string DIRECTORY = 'docs/for-it-admins/idp';

    public const string INDEX = self::DIRECTORY.'/_index.md';

    public const string BEGIN = '<!-- BEGIN GENERATED by `php artisan docs:idp-guides` — edit the command, never this table. -->';

    public const string END = '<!-- END GENERATED -->';

    /** Guide key => the hand-written page that covers it. */
    public const array HAND_WRITTEN = [
        'okta' => 'okta.md',
        'entra' => 'entra-id.md',
        'google' => 'google-workspace.md',
        'saml' => 'generic-saml.md',
        'oidc' => 'generic-oidc.md',
    ];

    /** The first generated page's `weight`, after the hand-written ones. */
    private const int FIRST_WEIGHT = 100;

    /**
     * Every generated page, as path relative to the repository root => content.
     *
     * @return array<string, string>
     */
    public function pages(): array
    {
        $pages = [];
        $weight = self::FIRST_WEIGHT;

        foreach (IdentityProviderGuides::all() as $guide) {
            if (isset(self::HAND_WRITTEN[$guide->key])) {
                continue;
            }

            $pages[self::DIRECTORY.'/'.self::file($guide->key)] = $this->page($guide, $weight);
            $weight += 10;
        }

        return $pages;
    }

    /** The index with its provider table rebuilt, or null when the markers are missing. */
    public function index(string $current): ?string
    {
        $begin = strpos($current, self::BEGIN);
        $end = strpos($current, self::END);

        if ($begin === false || $end === false || $end < $begin) {
            return null;
        }

        return substr($current, 0, $begin + strlen(self::BEGIN))."\n\n".$this->table()."\n".substr($current, $end);
    }

    public static function file(string $key): string
    {
        return self::HAND_WRITTEN[$key] ?? $key.'.md';
    }

    private function table(): string
    {
        $rows = ['| Provider | Enterprise SSO | Directory Sync |', '|---|---|---|'];

        foreach (IdentityProviderGuides::all() as $guide) {
            if (in_array($guide->key, ['saml', 'oidc'], true)) {
                continue;
            }

            $directory = match (true) {
                $guide->directory !== null => 'SCIM',
                $guide->key === 'google' => 'Not over SCIM; see the page',
                // No guide is not "cannot": the framework writes one only where it verified a
                // custom-app SCIM push with a bearer token.
                default => 'Not guided; [SCIM 2.0](generic-scim.md) if it can push with a bearer token',
            };

            $rows[] = '| ['.$guide->name.']('.self::file($guide->key).') | '.$guide->protocol->label().' | '.$directory.' |';
        }

        $rows[] = '| Anything else | [SAML 2.0](generic-saml.md) or [OpenID Connect](generic-oidc.md) | [SCIM 2.0](generic-scim.md) |';

        return implode("\n", $rows)."\n";
    }

    private function page(IdentityProviderGuide $guide, int $weight): string
    {
        $saml = $guide->protocol === GuideProtocol::Saml;
        $what = 'single sign-on ('.$guide->protocol->label().')'.($guide->directory !== null ? ' and Directory Sync (SCIM)' : '');

        $lines = [
            '---',
            'title: '.$guide->name,
            'weight: '.$weight,
            'description: Set up '.$what.' with '.$guide->name.' for the setup portal — the steps, which value goes into which '.$guide->name.' field, and what to bring back.',
            '---',
            '',
            '<!-- GENERATED by `php artisan docs:idp-guides` from laravel-id\'s IdentityProviderGuides.',
            '     Edit the framework guide or the command, never this file; `php artisan docs:idp-guides --check` fails when it is stale. -->',
            '',
            '# '.$guide->name,
            '',
            '## Single sign-on ('.$guide->protocol->label().')',
            '',
            'In the portal, choose **'.$guide->name.'** under Enterprise SSO and **Start with '.$guide->name.'**. Then, in '.$guide->name.':',
            '',
            ...self::steps($guide->setupSteps),
            '',
            '### The values the portal shows',
            '',
            ...$this->fields($guide->name, $guide->fields),
            '',
            '### What to bring back',
            '',
            $this->returns($guide),
        ];

        if ($saml) {
            $lines[] = '';
            $lines[] = 'The assertion must be signed, and must carry the person\'s email address as an attribute or as a NameID in the `emailAddress` format. See [Any SAML 2.0 provider](generic-saml.md) for the details.';
        }

        if ($guide->documentationUrl !== null) {
            $lines[] = '';
            $lines[] = $guide->name.'\'s own guide: <'.$guide->documentationUrl.'>.';
        }

        $lines[] = '';
        $lines[] = 'Then verify your domain and turn single sign-on on in the portal: [Enterprise SSO](../sso.md).';

        if ($guide->directory !== null) {
            array_push($lines, '', ...$this->directory($guide->name, $guide->directory));
        }

        array_push(
            $lines,
            '',
            '## Related',
            '',
            '- [Identity provider guides](_index.md) — every provider the portal guides you through.',
            '- [Enterprise SSO](../sso.md) — the portal\'s five steps.',
        );

        if ($guide->directory !== null) {
            $lines[] = '- [Directory Sync](../directory-sync.md) — the portal\'s SCIM setup.';
        }

        return implode("\n", $lines)."\n";
    }

    /** @return list<string> */
    private function directory(string $name, ScimDirectoryGuide $directory): array
    {
        $lines = [
            '## Directory Sync (SCIM)',
            '',
            'In the portal, choose **'.$name.'** under Directory sync and **Create directory**; copy the bearer token now, it is shown once. Then, in '.$name.':',
            '',
            ...self::steps($directory->setupSteps),
            '',
            '### The values the portal shows',
            '',
            ...$this->fields($name, $directory->fields),
        ];

        if ($directory->documentationUrl !== null) {
            $lines[] = '';
            $lines[] = $name.'\'s own guide: <'.$directory->documentationUrl.'>.';
        }

        return $lines;
    }

    /**
     * @param  list<string>  $steps
     * @return list<string>
     */
    private static function steps(array $steps): array
    {
        $lines = [];

        foreach ($steps as $number => $step) {
            $lines[] = ($number + 1).'. '.self::escape($step);
        }

        return $lines;
    }

    /**
     * @param  list<GuideField>  $fields
     * @return list<string>
     */
    private function fields(string $name, array $fields): array
    {
        $rows = ['| '.$name.' field | Value |', '|---|---|'];

        foreach ($fields as $field) {
            $label = self::escape($field->theirs);

            if ($field->location !== null) {
                $label .= ' ('.self::escape($field->location).')';
            }

            if ($field->optional) {
                $label .= ', optional';
            }

            $rows[] = '| '.$label.' | '.self::value($field).' |';
        }

        return $rows;
    }

    private function returns(IdentityProviderGuide $guide): string
    {
        $theirs = '**'.self::escape($guide->returns->theirs).'**';

        return match ($guide->returns->kind) {
            GuideReturnKind::Url => 'Copy '.$theirs.' and paste it into the portal\'s **Metadata URL or XML**.',
            GuideReturnKind::Xml => 'Get '.$theirs.' and paste the XML into the portal\'s **Metadata URL or XML**.',
            GuideReturnKind::UrlOrXml => 'Copy '.$theirs.' — the URL, or the XML — and paste it into the portal\'s **Metadata URL or XML**. Prefer the URL.',
            GuideReturnKind::Oidc => 'Enter '.$theirs.' in the portal.',
        };
    }

    private static function value(GuideField $field): string
    {
        return match ($field->ours) {
            SpValue::Literal => '`'.str_replace('|', '\\|', (string) $field->literal).'`',
            SpValue::AcsUrl => 'The portal\'s ACS URL (`https://…/sso/saml/…/acs`)',
            SpValue::EntityId => 'The portal\'s entity ID (`https://…/sso/saml/…`)',
            SpValue::SpMetadataUrl => 'The portal\'s SP metadata URL (`https://…/sso/saml/…/metadata`)',
            SpValue::SloUrl => 'The portal\'s Single Logout URL (`https://…/sso/saml/…/slo`)',
            SpValue::LoginUrl => 'The portal\'s sign-in URL (`https://…/sso/saml/…/login`)',
            SpValue::RedirectUri => 'The portal\'s redirect URI (`https://…/sso/oidc/…/callback`)',
            SpValue::AcsUrlPattern => 'A pattern matching exactly the ACS URL; the portal shows it',
            SpValue::ScimBaseUrl => 'The portal\'s SCIM base URL (`https://…/scim/v2`)',
            SpValue::ScimHost => 'The host of the portal\'s SCIM base URL',
            SpValue::ScimBasePath => 'The path of the portal\'s SCIM base URL (`/scim/v2`)',
            SpValue::ScimToken => 'The bearer token the portal shows once',
        };
    }

    /** A guide's text in a Markdown table cell or list item: no pipes, no stray tags. */
    private static function escape(string $text): string
    {
        return str_replace(['|', '<', '>'], ['\\|', '&lt;', '&gt;'], $text);
    }
}
