<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A user's enrolled mobile device — the thing a CIBA approval prompt is pushed to.
 *
 * `install_id` is generated by the app and kept in the platform keystore, NOT derived
 * from a vendor device identifier. iOS `identifierForVendor` and Android `ANDROID_ID`
 * both reset on reinstall and are shared across one vendor's apps, so keying on them
 * would either orphan a device on every reinstall or collide two apps. The unique key
 * is (environment, subject, install) so re-enrolment after an FCM token rotation
 * updates the existing row instead of accumulating dead ones.
 *
 * The push token is SEALED rather than stored plainly. It is a capability: anyone
 * holding it plus the project's FCM credentials can push to that handset. The same
 * treatment webhook endpoint secrets get, for the same reason.
 *
 * The four circuit-breaker columns live here rather than in cache so a device that has
 * gone dark stays visible in the console and survives a cache flush. They are health,
 * not intent — `status` is the operator/user decision, and the two are deliberately
 * separate concerns.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('id_devices', function (Blueprint $table): void {
            // string(26), never ulid(): ulid() compiles to char(26), and Postgres
            // blank-pads CHAR so the value read back never === the value written.
            // That broke environment scoping and the audit hash chain repo-wide.
            $table->string('id', 26)->primary();
            $table->string('environment_id', 26)->index();
            $table->string('subject_id', 26)->index();
            $table->string('install_id', 26);

            $table->string('platform', 16);
            $table->string('name', 100);
            $table->string('status', 16);

            // Nullable because a retired device keeps its row (for the audit trail and
            // the console list) but must not keep a live push capability.
            $table->text('token_encrypted')->nullable();

            // Recorded from the VERIFIED DPoP proof, never from the request body. Used
            // to spot a key change on an install that never re-enrolled.
            $table->string('dpop_jkt', 64)->nullable();

            $table->string('app_version', 32)->nullable();
            $table->string('os_version', 32)->nullable();
            $table->string('model', 64)->nullable();

            $table->timestamp('last_seen_at')->nullable();
            $table->timestamp('token_rotated_at')->nullable();

            // High-water mark for this device's notification sequence, allocated under
            // a row lock. Kept here rather than derived from max(sequence) on the
            // notifications table so the lock is on one narrow row instead of a range
            // of the table being appended to.
            $table->unsignedBigInteger('last_sequence')->default(0);

            $table->unsignedInteger('consecutive_failures')->default(0);
            $table->timestamp('circuit_opened_at')->nullable();
            $table->timestamp('last_success_at')->nullable();
            $table->string('last_error', 255)->nullable();

            $table->timestamps();

            // Unique on (environment, install) — deliberately WITHOUT subject_id.
            //
            // The enrolment endpoint treats an install as belonging to at most one
            // subject: finding one owned by somebody else is a 409 rather than a
            // reassignment, because silently moving it would let one user capture
            // another's push stream by guessing an install id. Including subject_id here
            // would let the database hold two rows the controller believes cannot both
            // exist — two concurrent enrolments would each see no conflict and both
            // insert, after which the ownership lookup is order-dependent and one of the
            // two users is permanently locked out of token rotation.
            //
            // Named explicitly: the generated name would exceed Postgres's 63-char
            // identifier cap and be silently truncated into a collision risk.
            $table->unique(['environment_id', 'install_id'], 'id_devices_env_install_uq');
            // The delivery fan-out: every active device for one subject.
            $table->index(['environment_id', 'subject_id', 'status'], 'id_devices_env_subject_status_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('id_devices');
    }
};
