<?php

declare(strict_types=1);
use App\Platform\Actions\ActionPlane;
use App\Platform\Actions\ActionRegistry;
use Symfony\Component\Yaml\Yaml;

/*
| The committed OpenAPI documents — one per plane — are exactly what their base and the
| action registry build. A new action is documented by building, never by hand; this is what
| fails when nobody did.
*/

it('commits the OpenAPI documents the bases and the actions build', function (): void {
    $this->artisan('openapi:build', ['--check' => true])->assertSuccessful();
});

it('documents every action in its own plane\'s document, as the action declares it', function (ActionPlane $plane): void {
    $spec = Yaml::parseFile(resource_path("openapi/{$plane->value}.yaml"));

    foreach (app(ActionRegistry::class)->forPlane($plane) as $action) {
        expect($spec['paths'][$action->documentedPath()][strtolower($action->method)] ?? null)
            ->toBeArray("{$action->name} is not in the {$plane->value} OpenAPI document");
    }
})->with(ActionPlane::cases());

it('builds each document from its own hand-written base', function (ActionPlane $plane): void {
    expect(resource_path("openapi/base/{$plane->value}.yaml"))->toBeFile()
        ->and((string) file_get_contents(resource_path("openapi/{$plane->value}.yaml")))
        ->toStartWith("# GENERATED by `php artisan openapi:build` from resources/openapi/base/{$plane->value}.yaml");
})->with(ActionPlane::cases());
