<?php

declare(strict_types=1);
use App\Platform\Actions\ActionPlane;
use App\Platform\Actions\ActionRegistry;
use App\Platform\Actions\OpenApi\ActionOpenApi;
use Symfony\Component\Yaml\Yaml;

/*
| The committed OpenAPI documents — one per plane — are exactly what their base and the
| action registry build. A new action is documented by building, never by hand; this is what
| fails when nobody did.
*/

it('commits the OpenAPI documents the bases and the actions build', function (): void {
    $this->artisan('openapi:build', ['--check' => true])->assertSuccessful();
});

it('documents every action in its own plane\'s document, as the action declares it', function (ActionPlane $plane): void {
    $spec = Yaml::parseFile(resource_path("openapi/{$plane->value}.yaml"));

    foreach (app(ActionRegistry::class)->forPlane($plane) as $action) {
        expect($spec['paths'][$action->documentedPath()][strtolower($action->method)] ?? null)
            ->toBeArray("{$action->name} is not in the {$plane->value} OpenAPI document");
    }
})->with(ActionPlane::cases());

it('builds each document from its own hand-written base', function (ActionPlane $plane): void {
    expect(resource_path("openapi/base/{$plane->value}.yaml"))->toBeFile()
        ->and((string) file_get_contents(resource_path("openapi/{$plane->value}.yaml")))
        ->toStartWith("# GENERATED by `php artisan openapi:build` from resources/openapi/base/{$plane->value}.yaml");
})->with(ActionPlane::cases());

it('keeps the approval hold\'s body in step with every plane\'s ApprovalRequired response', function (ActionPlane $plane): void {
    $base = Yaml::parseFile(resource_path("openapi/base/{$plane->value}.yaml"));

    expect($base['components']['responses']['ApprovalRequired']['content']['application/json']['schema'] ?? null)
        ->toEqual(ActionOpenApi::APPROVAL_REQUIRED);
})->with(ActionPlane::cases());

/*
 * An action whose own answer is 202 (a queued directory sync) shares the status with the
 * approval hold. The hold used to overwrite it, so every generated client lost the action's
 * real answer — the PHP generator refused the operation outright.
 */
it('documents both answers of an action that itself answers 202', function (): void {
    $actions = collect(app(ActionRegistry::class)->all())->filter(fn ($action): bool => $action->status === 202);

    expect($actions)->not->toBeEmpty();

    foreach ($actions as $action) {
        $spec = Yaml::parseFile(resource_path("openapi/{$action->plane->value}.yaml"));
        $accepted = $spec['paths'][$action->documentedPath()][strtolower($action->method)]['responses'][202] ?? null;

        expect($accepted['content']['application/json']['schema']['oneOf'] ?? null)
            ->toBeArray("{$action->name}'s 202 does not offer both bodies")
            ->toHaveCount(2)
            ->and($accepted['content']['application/json']['schema']['oneOf'][1])->toEqual(ActionOpenApi::APPROVAL_REQUIRED);
    }
});
