<?php

declare(strict_types=1);

namespace App\Platform\Actions\Reference;

use App\Console\Commands\BuildActionsReferenceCommand;
use App\Platform\Actions\ActionDefinition;
use App\Platform\Actions\ActionPlane;
use App\Platform\Actions\ActionRegistry;
use App\Platform\Actions\OpenApi\ActionOpenApi;

/**
 * THE ACTIONS REFERENCE — one Markdown page per {@see ActionPlane}, written from the
 * action registry by `php artisan docs:actions` ({@see BuildActionsReferenceCommand}).
 *
 * An action is reached through four doors — the console, REST, MCP and the `cbox` CLI —
 * and each door derives its surface from the same {@see ActionDefinition}: the REST
 * route from its method and path, the MCP tool from its name with dots as underscores,
 * the CLI command from its name with dots as words. So the page a developer reads to
 * find "how do I do X from my agent" is generated from those same facts, and cannot
 * describe a tool name or a path the server does not serve. A new action is in the
 * reference the moment the build runs; `--check` and its test fail the day somebody
 * adds one without running it.
 *
 * Deterministic on purpose: the registry is name-ordered, nothing here reads a clock or
 * a host, and the scope sentence is {@see ActionOpenApi::requirement()} verbatim — the
 * same words the OpenAPI document carries, so the two references cannot disagree about
 * what a key needs.
 */
final readonly class ActionsReference
{
    public function __construct(
        private ActionRegistry $registry,
        private ActionOpenApi $openApi,
    ) {}

    /** Where the page for $plane is written, relative to the repository root. */
    public static function path(ActionPlane $plane): string
    {
        return "docs/reference/actions-{$plane->value}.md";
    }

    /** The whole page for $plane, front matter included. */
    public function render(ActionPlane $plane): string
    {
        $actions = $this->registry->forPlane($plane);

        /** @var array<string, list<ActionDefinition>> $byTag */
        $byTag = [];

        foreach ($actions as $action) {
            $byTag[$this->openApi->tag($action)][] = $action;
        }

        ksort($byTag, SORT_NATURAL | SORT_FLAG_CASE);

        $lines = [
            '---',
            'title: '.$this->title($plane),
            'weight: '.$this->weight($plane),
            'description: '.$this->description($plane, count($actions)),
            '---',
            '',
            '<!-- GENERATED by `php artisan docs:actions` from the action registry (app/Actions).',
            '     Edit the action, never this file; `php artisan docs:actions --check` fails when it is stale. -->',
            '',
            '# '.$this->title($plane),
            '',
            ...$this->intro($plane),
            '',
            '| | |',
            '|---|---|',
            ...$this->doors($plane),
            '',
            'Danger is how much harm the action can do in the wrong hands: `read` only reads; `write` changes something another write can undo; `destructive` removes or revokes; `critical` mints credentials, takes over access or changes how people sign in. MCP clients are told a destructive or critical tool is destructive, the CLI asks before running one, and an [approval policy](../core-concepts/approvals.md) keys on it.',
            '',
            '## Contents',
            '',
            '| Area | Actions |',
            '|---|---|',
        ];

        foreach ($byTag as $tag => $tagged) {
            $lines[] = '| ['.$tag.'](#'.self::slug($tag).') | '.implode(', ', array_map(
                static fn (ActionDefinition $action): string => '[`'.$action->name.'`](#'.self::anchor($action).')',
                $tagged,
            )).' |';
        }

        foreach ($byTag as $tag => $tagged) {
            $lines[] = '';
            $lines[] = '## '.$tag;

            foreach ($tagged as $action) {
                $lines = [...$lines, '', ...$this->action($action)];
            }
        }

        return implode("\n", $lines)."\n";
    }

    /**
     * The heading anchor a Markdown renderer gives $heading — GitHub's rule: lowercase,
     * punctuation other than `-` and `_` dropped, spaces to hyphens. `App audit logs` is
     * `#app-audit-logs`.
     *
     * Used for the AREA headings only, whose names have no `_`: there GitHub and the docs
     * site (cbox.dk, league/commonmark's slug, which drops `_` as well) agree, and
     * tests/Feature/DocsLinksTest.php fails the moment an anchor works on one and not
     * the other. An action's name has `_` in it, so an action is linked by
     * {@see anchor()} instead.
     */
    public static function slug(string $heading): string
    {
        $slug = mb_strtolower(trim($heading));
        $slug = (string) preg_replace('/[^\p{L}\p{N}\s_-]/u', '', $slug);

        return str_replace(' ', '-', $slug);
    }

    /**
     * The anchor an action is linked by: its own name, set on its heading explicitly.
     *
     * Not the heading's slug, because the two renderers that publish this page slug
     * `organizations.portal_links.create` differently: GitHub keeps the `_`
     * (`#organizationsportal_linkscreate`) and the docs site drops it
     * (`#organizationsportallinkscreate`), so every Contents link to an action with an
     * underscore was dead on cbox.dk while it worked on GitHub. An explicit
     * `<a id="…">` is the same id on both, and the name is the anchor a reader would
     * guess.
     */
    public static function anchor(ActionDefinition $action): string
    {
        return $action->name;
    }

    /**
     * One action: what it does, the four doors to it, and its input.
     *
     * @return list<string>
     */
    private function action(ActionDefinition $action): array
    {
        $fields = $this->fields($action);

        $lines = [
            '### <a id="'.self::anchor($action).'"></a>'.$action->name,
            '',
            $action->summary,
            '',
            '| | |',
            '|---|---|',
            '| REST | `'.$action->method.' /api/v1'.$action->documentedPath().'` → `'.$action->status.'` |',
            '| Scope | `'.$action->scope.'` — '.$this->scopeSentence($action).' |',
            '| Danger | `'.$action->danger->value.'` |',
            '| MCP tool | `'.$action->toolName().'` |',
            '| CLI | `'.$this->cli($action).'` |',
        ];

        if ($action->redact !== []) {
            $lines[] = '| Secret | '.implode(', ', array_map(static fn (string $field): string => '`data.'.$field.'`', $action->redact)).' — shown once, never kept for an idempotent replay |';
        }

        $lines[] = '';

        if ($fields === []) {
            $lines[] = 'Takes no input.';

            return $lines;
        }

        $lines[] = '| Input | Type | Required | Description |';
        $lines[] = '|---|---|---|---|';

        foreach ($fields as [$name, $type, $required, $description]) {
            $lines[] = '| `'.$name.'` | '.$type.' | '.($required ? 'yes' : 'no').' | '.$description.' |';
        }

        return $lines;
    }

    /** The requirement sentence the OpenAPI document carries, without its leading "Requires scope `x`". */
    private function scopeSentence(ActionDefinition $action): string
    {
        $sentence = $this->openApi->requirement($action);
        $sentence = (string) preg_replace('/^Requires scope `[^`]+`\s*/', '', $sentence);

        return $sentence === '.' || $sentence === '' ? 'required of the key or token.' : ltrim($sentence, ' ');
    }

    /** `cbox id apps secrets rotate <app_id>` — the action's name as words, path arguments in order. */
    private function cli(ActionDefinition $action): string
    {
        $arguments = array_map(static fn (string $field): string => '<'.$field.'>', $action->input()->pathFields());

        // Path arguments in the order the PATH names them, which is how the CLI takes them.
        usort($arguments, static fn (string $a, string $b): int => strpos($action->path, '{'.trim($a, '<>').'}') <=> strpos($action->path, '{'.trim($b, '<>').'}'));

        return trim('cbox id '.str_replace('.', ' ', $action->name).' '.implode(' ', $arguments));
    }

    /**
     * Every input as a table row, an object's members flattened to `parent.member`.
     *
     * @return list<array{0: string, 1: string, 2: bool, 3: string}>
     */
    private function fields(ActionDefinition $action): array
    {
        $schema = $action->input()->jsonSchema();
        $inPath = $action->input()->pathFields();

        return $this->rows($schema, '', $inPath);
    }

    /**
     * @param  array<string, mixed>  $schema  An `object` schema.
     * @param  list<string>  $inPath
     * @return list<array{0: string, 1: string, 2: bool, 3: string}>
     */
    private function rows(array $schema, string $prefix, array $inPath = []): array
    {
        $properties = is_array($schema['properties'] ?? null) ? $schema['properties'] : [];
        $required = is_array($schema['required'] ?? null) ? $schema['required'] : [];
        $rows = [];

        foreach ($properties as $name => $property) {
            if (! is_array($property)) {
                continue;
            }

            /** @var array<string, mixed> $property */
            $name = (string) $name;
            $type = $this->type($property);

            if ($prefix === '' && in_array($name, $inPath, true)) {
                $type .= ' (path)';
            }

            $rows[] = [$prefix.$name, $type, in_array($name, $required, true), $this->describe($property)];

            if (($property['type'] ?? null) === 'object' || (is_array($property['type'] ?? null) && in_array('object', $property['type'], true))) {
                $rows = [...$rows, ...$this->rows($property, $prefix.$name.'.')];
            }

            $items = $property['items'] ?? null;

            if (is_array($items) && ($items['type'] ?? null) === 'object') {
                /** @var array<string, mixed> $items */
                $rows = [...$rows, ...$this->rows($items, $prefix.$name.'[].')];
            }
        }

        return $rows;
    }

    /** @param  array<string, mixed>  $property */
    private function type(array $property): string
    {
        $types = is_array($property['type'] ?? null) ? $property['type'] : [$property['type'] ?? 'any'];
        $nullable = in_array('null', $types, true);
        $type = array_values(array_filter($types, static fn (mixed $type): bool => is_string($type) && $type !== 'null'))[0] ?? 'any';

        if ($type === 'array' && is_array($property['items'] ?? null)) {
            /** @var array<string, mixed> $items */
            $items = $property['items'];
            $type = 'list of '.$this->type($items);
        }

        if (is_string($property['format'] ?? null)) {
            $type .= ' ('.$property['format'].')';
        }

        return $nullable ? $type.', nullable' : $type;
    }

    /** @param  array<string, mixed>  $property */
    private function describe(array $property): string
    {
        $parts = [];

        if (is_string($property['description'] ?? null)) {
            $parts[] = rtrim($property['description']);
        }

        if (is_array($property['enum'] ?? null)) {
            $parts[] = 'One of '.implode(', ', array_map(static fn (mixed $value): string => '`'.(is_scalar($value) ? (string) $value : '').'`', $property['enum'])).'.';
        }

        foreach (['minLength' => 'At least %d characters.', 'maxLength' => 'At most %d characters.', 'minimum' => 'At least %d.', 'maximum' => 'At most %d.', 'minItems' => 'At least %d items.', 'maxItems' => 'At most %d items.'] as $key => $format) {
            if (is_int($property[$key] ?? null)) {
                $parts[] = sprintf($format, $property[$key]);
            }
        }

        // A table cell is one line, and a pipe would end it.
        return str_replace(['|', "\n"], ['\\|', ' '], implode(' ', $parts));
    }

    private function title(ActionPlane $plane): string
    {
        return match ($plane) {
            ActionPlane::Environment => 'Environment actions',
            ActionPlane::Workspace => 'Workspace actions',
            ActionPlane::Account => 'Account actions',
            ActionPlane::Platform => 'Platform actions',
        };
    }

    private function weight(ActionPlane $plane): int
    {
        return match ($plane) {
            ActionPlane::Environment => 20,
            ActionPlane::Workspace => 30,
            ActionPlane::Account => 40,
            ActionPlane::Platform => 50,
        };
    }

    private function description(ActionPlane $plane, int $count): string
    {
        return match ($plane) {
            ActionPlane::Environment => "All {$count} actions inside one environment — organizations, users, apps, APIs, keys, sign-in, governance — with their REST route, scope, danger, MCP tool and CLI command.",
            ActionPlane::Workspace => "All {$count} workspace actions — projects, environments, the team and keys — with their REST route, scope, danger, MCP tool and CLI command.",
            ActionPlane::Account => "All {$count} actions a person runs on their own account — sessions, app grants, personal keys, devices — with their REST route, scope, danger, MCP tool and CLI command.",
            ActionPlane::Platform => "All {$count} platform-operator actions on the deployment itself, with their REST route, scope, danger, MCP tool and CLI command.",
        };
    }

    /** @return list<string> */
    private function intro(ActionPlane $plane): array
    {
        $common = 'Every row below is one action, reached through four doors that run the same code, with the same authorization, validation, approvals and [Audit log](../guides/activity-log.md) entry: the console, the REST API, the MCP server and the `cbox` CLI. See [Actions](../core-concepts/actions.md) for how that works and [Planes and hosts](../core-concepts/planes-and-hosts.md) for where each plane is served.';

        return match ($plane) {
            ActionPlane::Environment => [
                'The environment plane is everything inside **one environment**: its organizations, users, applications, APIs, keys, sign-in configuration and governance. It is served on the environment\'s own host.',
                '',
                $common,
            ],
            ActionPlane::Workspace => [
                'The workspace plane is the customer\'s own Cbox account, above every environment it owns: projects, environments (and their custom domains), the team, workspace keys and the keys of each environment. It is served on the platform root and resolves no environment.',
                '',
                $common,
            ],
            ActionPlane::Account => [
                'The account plane is **one person\'s own account**: their profile, sessions, the apps they have allowed to act for them, their personal API keys and trusted devices. Only that person reaches it — in the console, or through a token they delegated. No management key acts as a person, and there is no account id in any path.',
                '',
                $common,
            ],
            ActionPlane::Platform => [
                'The platform plane is **the deployment itself**, for the people who run the install: workspaces, environments, organizations inside any environment, and the operator roster. No key of any kind reaches it — only a platform operator, in the console or through a token they delegated, carrying the `operator:*` scope an action asks for.',
                '',
                $common,
            ],
        };
    }

    /**
     * How each door reaches this plane.
     *
     * @return list<string>
     */
    private function doors(ActionPlane $plane): array
    {
        // Served by every deployment without a key; the committed copy is linked by its
        // canonical URL, because a docs site renders docs/ and nothing beside it.
        $served = $plane === ActionPlane::Account ? '/api/v1/me/openapi.yaml' : '/api/v1/'.$plane->value.'/openapi.yaml';
        $openApi = '| OpenAPI | `'.$served.'` on the host above — public, no key needed ([source](https://github.com/cboxdk/cbox-id/blob/main/resources/openapi/'.$plane->value.'.yaml)); every operation carries `x-action`, `x-scope` and `x-danger` |';

        return match ($plane) {
            ActionPlane::Environment => [
                '| REST | `https://<environment-host>/api/v1/…` with `Authorization: Bearer cbid_env_…` (a secret key of that environment), or a token a person delegated. At the platform root, a team member\'s token names the environment in a `Cbox-Environment` header |',
                '| MCP | `/mcp` on the environment\'s host. At the platform root\'s `/mcp`, every environment tool takes an `environment` argument (an id or slug from `whoami`) |',
                '| CLI | `cbox login`, `cbox id use <environment>`, then the command below — or `CBOX_ID_ENDPOINT` + `CBOX_ID_TOKEN=cbid_env_…` for CI |',
                $openApi,
            ],
            ActionPlane::Workspace => [
                '| REST | `https://<root-host>/api/v1/workspace/…` with `Authorization: Bearer cbid_ws_…` (a workspace key, whose role must also allow the action), or a team member\'s token from the root |',
                '| MCP | `/mcp` on the platform root, signed in as a member of the workspace\'s team, or with a workspace key |',
                '| CLI | `cbox login` at the root, then the command below |',
                $openApi,
            ],
            ActionPlane::Account => [
                '| REST | `https://<host>/api/v1/me/…` with a token you delegated — on your environment\'s host, or on the platform root for a workspace team member or operator |',
                '| MCP | `/mcp` on the same host, signed in as yourself |',
                '| CLI | `cbox login`, then the command below |',
                $openApi,
            ],
            ActionPlane::Platform => [
                '| REST | `https://<root-host>/api/v1/platform/…` with a token the platform root issued a platform operator. No key is accepted |',
                '| MCP | `/mcp` on the platform root, signed in as a platform operator |',
                '| CLI | `cbox login` at the root as an operator, then the command below |',
                $openApi,
            ],
        };
    }
}
