<?php

declare(strict_types=1);

namespace Tests\Support;

use Tests\Feature\Actions\ActionParityTest;

/**
 * Console writes that are not (yet) an action: the debt the parity test holds to a number
 * that only goes down ({@see ActionParityTest}).
 *
 * Kept in kinds, because only one of them is debt:
 *
 *  - CEREMONIES a person performs in a browser: signing in, a second factor, consenting,
 *    accepting an invitation, confirming a password, choosing which console to look at.
 *    They are UI by nature; an API for them would be an API for impersonating the person.
 *  - The ADMIN PORTAL's own steps, taken by a customer's IT admin holding a one-time link.
 *    What a machine needs there is the LINK, which is an action of its own.
 *  - OPERATOR TOOLING from a vendor package (the queue monitor's dashboard).
 *  - PENDING: real management writes with no action yet. Every one is something an agent
 *    cannot do. Moving one into an action removes it from this list.
 */
final class ParityAllowlist
{
    /** The most PENDING entries there may be. Lower it whenever an area becomes actions. */
    public const int BASELINE = 233;

    /** @return list<string> */
    public static function ceremonies(): array
    {
        return [
            'account.mfa.confirm',
            'account.mfa.enrol',
            'account.mfa.recovery-codes',
            'account.password.update',
            'accounts.switch',
            'admin.logout',
            'dashboard.checklist.dismiss',
            'device.approve',
            'device.deny',
            'device.lookup',
            'environment.acting-organization.choose',
            'environment.acting-organization.clear',
            'environment.sudo.confirm',
            'first-run.claim',
            'frontend.sign-in',
            'frontend.sign-in.factor',
            'frontend.sign-in.passkey',
            'frontend.sign-in.passkey.options',
            'get-started.dismiss',
            'impersonation.exit',
            'invitation.accept.store',
            'link.connect',
            'link.decline',
            'login.attempt',
            'login.identify',
            'login.magic-link',
            'login.step-up.resend',
            'login.step-up.verify',
            'logout',
            'magic.redeem.store',
            'mfa.recover',
            'mfa.verify',
            'oauth.authorize.approve',
            'oauth.authorize.deny',
            'oauth.authorize.organization.choose',
            'oauth.authorize.organization.store',
            'organization.invite.accept.store',
            'organization.switch',
            'passkeys.login',
            'passkeys.login.options',
            'passkeys.register',
            'passkeys.register.options',
            'password.change.update',
            'password.email',
            'password.update',
            'platform.customers.open',
            'platform.customers.target',
            'platform.environment.switch',
            'portal.enter.store',
            'portal.finish',
            'signup.register',
            'sso.saml.acs',
            'sudo.confirm',
            'verification.verify.store',
        ];
    }

    /** @return list<string> */
    public static function adminPortal(): array
    {
        return [
            'portal.connections.activate',
            'portal.connections.store',
            'portal.directories.store',
            'portal.domains.destroy',
            'portal.domains.store',
            'portal.domains.verify',
        ];
    }

    /** @return list<string> */
    public static function operatorTooling(): array
    {
        return [
            'queue-monitor.dashboard.batch.delete',
            'queue-monitor.dashboard.batch.replay',
            'queue-monitor.dashboard.job.destroy',
            'queue-monitor.dashboard.job.replay',
            'queue-monitor.dashboard.stuck-jobs.resolve',
            'queue-monitor.dashboard.stuck-jobs.resolve-all',
        ];
    }

    /** @return list<string> */
    public static function pending(): array
    {
        return [
            'account.api-keys.revoke',
            'account.api-keys.store',
            'account.applications.destroy',
            'account.passkeys.destroy',
            'account.profile.update',
            'account.sessions.revoke',
            'account.sessions.revoke-others',
            'account.social.destroy',
            'appearance.update',
            'approvals.approve',
            'approvals.deny',
            'audit-streams.destroy',
            'audit-streams.store',
            'audit-streams.toggle',
            'auth-policy.inherit',
            'auth-policy.update',
            'clients.destroy',
            'clients.manifest',
            'clients.rotate',
            'clients.scopes.update',
            'clients.secrets.revoke',
            'clients.settings.api-keys',
            'clients.settings.exchange',
            'clients.settings.lifetime',
            'clients.settings.logout',
            'clients.store',
            'clients.sync',
            'clients.update',
            'compliance.data-exports.download',
            'connections.activate',
            'connections.destroy',
            'connections.disable',
            'connections.domains.capture',
            'connections.domains.destroy',
            'connections.domains.store',
            'connections.domains.verify',
            'connections.import',
            'connections.invite',
            'connections.require-sso',
            'connections.store',
            'connections.update',
            'devices.mine.destroy',
            'directories.connect',
            'directories.destroy',
            'directories.invite',
            'directories.map',
            'directories.rotate',
            'directories.store',
            'directories.toggle',
            'directories.update',
            'directory.api-keys.revoke',
            'directory.members.access',
            'directory.members.invitations.resend',
            'directory.members.invitations.revoke',
            'directory.members.invite',
            'directory.members.leave',
            'directory.members.remove',
            'directory.members.role',
            'directory.members.transfer-ownership',
            'environment-domains.destroy',
            'environment-domains.store',
            'environment-domains.verify',
            'environment.appearance.update',
            'environment.approvals.deny',
            'environment.audit-streams.destroy',
            'environment.audit-streams.store',
            'environment.audit-streams.toggle',
            'environment.auth-policy.inherit',
            'environment.auth-policy.self-service-signup',
            'environment.auth-policy.update',
            'environment.clients.copy',
            'environment.clients.destroy',
            'environment.clients.manifest',
            'environment.clients.rotate',
            'environment.clients.scopes.update',
            'environment.clients.secrets.revoke',
            'environment.clients.settings.api-keys',
            'environment.clients.settings.exchange',
            'environment.clients.settings.lifetime',
            'environment.clients.settings.logout',
            'environment.clients.store',
            'environment.clients.sync',
            'environment.clients.update',
            'environment.compliance.data-exports.download',
            'environment.connections.activate',
            'environment.connections.destroy',
            'environment.connections.disable',
            'environment.connections.domains.capture',
            'environment.connections.domains.destroy',
            'environment.connections.domains.store',
            'environment.connections.domains.verify',
            'environment.connections.import',
            'environment.connections.invite',
            'environment.connections.require-sso',
            'environment.connections.store',
            'environment.connections.update',
            'environment.directories.connect',
            'environment.directories.destroy',
            'environment.directories.invite',
            'environment.directories.map',
            'environment.directories.rotate',
            'environment.directories.store',
            'environment.directories.toggle',
            'environment.directories.update',
            'environment.governance.close',
            'environment.governance.item',
            'environment.governance.store',
            'environment.hooks.destroy',
            'environment.hooks.store',
            'environment.hooks.toggle',
            'environment.impersonate',
            'environment.keys.destroy',
            'environment.keys.frontend.destroy',
            'environment.keys.frontend.origins',
            'environment.keys.frontend.store',
            'environment.keys.store',
            'environment.legacy-login.approve',
            'environment.legacy-login.probe',
            'environment.legacy-login.revoke',
            'environment.organizations.api-keys.revoke',
            'environment.organizations.destroy',
            'environment.organizations.domains.capture',
            'environment.organizations.domains.remove',
            'environment.organizations.domains.store',
            'environment.organizations.domains.verify',
            'environment.organizations.invitations.resend',
            'environment.organizations.invitations.revoke',
            'environment.organizations.invitations.store',
            'environment.organizations.members.access',
            'environment.organizations.members.remove',
            'environment.organizations.members.role',
            'environment.organizations.members.store',
            'environment.organizations.members.transfer-ownership',
            'environment.organizations.reactivate',
            'environment.organizations.store',
            'environment.organizations.suspend',
            'environment.organizations.update',
            'environment.permissions.destroy',
            'environment.permissions.store',
            'environment.permissions.update',
            'environment.provisioning.destroy',
            'environment.provisioning.store',
            'environment.provisioning.toggle',
            'environment.roles.destroy',
            'environment.roles.permissions',
            'environment.roles.store',
            'environment.roles.update',
            'environment.settings.rename',
            'environment.social-providers.destroy',
            'environment.social-providers.store',
            'environment.sod-policies.destroy',
            'environment.sod-policies.store',
            'environment.sod-policies.toggle',
            'environment.sso-providers.destroy',
            'environment.sso-providers.store',
            'environment.sso-providers.update',
            'environment.staff.destroy',
            'environment.staff.store',
            'environment.support-sessions.end',
            'environment.users.deactivate',
            'environment.users.mfa',
            'environment.users.organizations.access',
            'environment.users.organizations.remove',
            'environment.users.organizations.role',
            'environment.users.organizations.store',
            'environment.users.password',
            'environment.users.password-reset',
            'environment.users.reactivate',
            'environment.users.roles',
            'environment.users.sessions.revoke',
            'environment.users.sessions.revoke-all',
            'environment.users.store',
            'environment.users.support-sessions.store',
            'environment.users.update',
            'environment.users.verification',
            'environment.users.verify',
            'environment.vault.grants.destroy',
            'environment.vault.grants.store',
            'environment.vault.revoke',
            'environment.vault.rotate',
            'environment.vault.store',
            'environment.webhooks.destroy',
            'environment.webhooks.pause',
            'environment.webhooks.resume',
            'environment.webhooks.rotate',
            'environment.webhooks.store',
            'environment.webhooks.update',
            'environment.whitelabel.branding.save',
            'governance.close',
            'governance.item',
            'governance.store',
            'hooks.destroy',
            'hooks.store',
            'hooks.toggle',
            'permissions.destroy',
            'permissions.store',
            'permissions.update',
            'platform.customers.store',
            'platform.customers.toggle',
            'platform.environments.provision',
            'platform.environments.store',
            'platform.impersonate',
            'platform.operators.store',
            'platform.operators.toggle',
            'platform.organizations.reparent',
            'platform.organizations.store',
            'platform.organizations.toggle',
            'provisioning.destroy',
            'provisioning.store',
            'provisioning.toggle',
            'roles.destroy',
            'roles.permissions',
            'roles.store',
            'roles.update',
            'settings.organization.destroy',
            'settings.rename',
            'social-providers.destroy',
            'social-providers.store',
            'sod-policies.destroy',
            'sod-policies.store',
            'sod-policies.toggle',
            'vault.grants.destroy',
            'vault.grants.store',
            'vault.revoke',
            'vault.rotate',
            'vault.store',
            'webhooks.destroy',
            'webhooks.pause',
            'webhooks.resume',
            'webhooks.rotate',
            'webhooks.store',
            'webhooks.update',
            'whitelabel.branding.save',
        ];
    }

    /** @return list<string> */
    public static function all(): array
    {
        return [...self::ceremonies(), ...self::adminPortal(), ...self::operatorTooling(), ...self::pending()];
    }
}
